matrix:
  allow_failures:
    - os: windows
#    - os: osx
    - os: linux
      env: BROWSER=opera
  include:
    - os: osx
      env: BROWSER=safari
      before_install:
        - curl -s http://get.sdkman.io | bash
        - source "$HOME/.sdkman/bin/sdkman-init.sh"
        - sdk install java 8.0.202-zulu
        - sudo safaridriver --enable # enable remote automation on safari
      script: ./gradlew clean test -Dbrowser=safari -Pserial # safari driver does not support parallel execution
    - os: linux
      env: BROWSER=firefox
      language: java
      jdk: openjdk8
      script: ./gradlew clean test -Dbrowser=firefox-headless
    - os: linux
      env: BROWSER=googlechrome
      language: java
      jdk: openjdk8
      addons:
        chrome: stable
      script: ./gradlew clean test # defaults to chrome-headless if no browser passed (see config.properties)
    - os: windows
      env: BROWSER=ie
      language: shell
      before_install:
        - choco install zip
        - choco install unzip
        - curl -s http://get.sdkman.io | bash
        - sdk install java 8.0.202-zulu
        - java -version
        - choco install ie11
      install: gradlew.bat clean test -Dbrowser=ie
    - os: linux
      env: BROWSER=opera
      language: java
      jdk: openjdk8
      dist: xenial
      addons:
        snaps:
          - opera
      script: ./gradlew clean test -Dbrowser=opera

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
